name: cage_example
description: A small example application using the cage framework
version: 0.1.0
author: Rouven T. Kruse
homepage: https://cage.pub
dependencies:
  cage:
    git:
      url: https://github.com/RTK/cage.git
      ref: develop
