name: cage
description: A flutter framework providing structure and guidance.
version: 1.1.0
author: Rouven T. Kruse <mail@rouvenkruse.de>
homepage: https://github.com/RTK/cage

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: "<=1.9.5"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.3+2
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
